name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/android-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Creer le projet Capacitor
        run: |
          mkdir capacitor-app
          cd capacitor-app

          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android

          mkdir www

          cat > www/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="fr">
          <head>
            <meta charset="UTF-8">
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            >
            <title>Mercedes-Benz</title>
          </head>

          <body>
            <p>Chargement de Mercedes-Benz...</p>

            <script>
              window.location.replace(
                "https://bayaya-devi.github.io/Mercedesbenz/"
              );
            </script>
          </body>
          </html>
          EOF

          npx cap init MercedesBenz com.bayaya.mercedesbenz --web-dir=www
          npx cap add android

      - name: Corriger les dependances Kotlin
        run: |
          cd capacitor-app/android

          cat >> app/build.gradle <<'EOF'

          configurations.all {
              resolutionStrategy {
                  force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
                  force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
                  force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
              }
          }
          EOF

      - name: Compiler APK
        run: |
          cd capacitor-app/android
          chmod +x gradlew
          ./gradlew clean assembleDebug

      - name: Sauvegarder APK
        uses: actions/upload-artifact@v4
        with:
          name: MercedesBenz-APK
          path: capacitor-app/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
